Add test for BundleBridge
chipsalliance/diplomacy pull request #11
Opened 2022-04-26 13:26 UTC by JACKLIAO0

This pull request adds test for BundleBridge, when running the Jacoco, the test coverage for bundlebridge file has reached 53%.

2022-07-14 02:01 UTC, sequencer requested changes

2022-07-14 02:30 UTC, JACKLIAO0 commented on diplomacy/test/src/BundleBridgeSpec.scala
> +        sinkModule.sink :*= sourceModule.source
I want to test  the iBindings of left side  is BIND_STAR   and oBindings the right side is  BIND_QUERY  when sink and source node are connectd with  :*=

2022-07-14 02:35 UTC, JACKLIAO0 commented on diplomacy/test/src/BundleBridgeSpec.scala
> +          // lazy val oPorts: Seq[(Int, InwardNode[DO, UO, BO], Parameters, SourceInfo)] = oDirectPorts.map(oTrace) := source
this line is definition of oPorts, to make the results of test more clearer

2022-07-14 03:33 UTC, JACKLIAO0 commented on diplomacy/test/src/BundleBridgeSpec.scala
> +          utest.assert(sinkModule.sink.doParams.isEmpty)
the case like multiple sink with one source is tested in BundleBridgeNexus : 

NexusLM.broadcastnode :*= sourceModule.source
sinkModule.sink :*= NexusLM.broadcastnode
OthersinkModule.sink := NexusLM.broadcastnode

2022-07-24 05:59 UTC, sequencer approved these changes
LGTM

2022-07-24 05:59 UTC, merged